### ISSUE TITLE
groups

### ISSUE THREAD

**Issue by lenerd** [lenerd/papo-project#3]
Da failed eine Assertion:

    ngg_tool: /home/lennart/uni/PAPO/project/git/code/src/go/board.c:178: board_capture_group: Assertion `group == board->group_id[group]' failed

backtrace

    #0  0x00000000051625f8 in raise () from /usr/lib/libc.so.6
    #1  0x0000000005163a7a in abort () from /usr/lib/libc.so.6
    #2  0x000000000515b417 in __assert_fail_base () from /usr/lib/libc.so.6
    #3  0x000000000515b4c2 in __assert_fail () from /usr/lib/libc.so.6
    #4  0x00000000004061df in board_capture_group (board=0x54d4bc0, group=0x19)
    at /home/lennart/uni/PAPO/project/git/code/src/go/board.c:178
    #5  0x000000000040651a in board_capture (board=0x54d4bc0, x=0x3, y=0x7)
    at /home/lennart/uni/PAPO/project/git/code/src/go/board.c:226
    #6  0x0000000000405d57 in board_place_color (board=0x54d4bc0, x=0x3, y=0x7, 
    color=c_black) at /home/lennart/uni/PAPO/project/git/code/src/go/board.c:97
    #7  0x0000000000405dc3 in board_place (board=0x54d4bc0, x=0x3, y=0x7)
    at /home/lennart/uni/PAPO/project/git/code/src/go/board.c:104
    #8  0x000000000040578f in td_generate_nxn_nxn (n=0xa)
    at /home/lennart/uni/PAPO/project/git/code/src/training/training.c:203
    #9  0x0000000000402651 in generate_training_data (opts=0xfff0000e0)
    at /home/lennart/uni/PAPO/project/git/code/src/exe/ngg_tool_impl.c:86
    #10 0x0000000000402378 in main (argc=0x9, argv=0xfff000228)
    at /home/lennart/uni/PAPO/project/git/code/src/exe/ngg_tool.c:182
    #11 0x000000000514f610 in __libc_start_main () from /usr/lib/libc.so.6
    #12 0x0000000000401e39 in _start ()

**Comment by lenerd** [comment]
Fehler tritt auf, wenn ein Stein gesetzt wird und mehrere benachbarte Steine in einer Gruppe sind. Diese wird auseinander gerissen.
